//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class ListItem
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="The name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage ="The Description is required")]
        public string Description { get; set; }
    }
}
